# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'Hacker News' do
	pod 'Alamofire', '~> 3.3'
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
end

target 'Hacker NewsTests' do

end