# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Hacker News' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hacker News

  target 'Hacker NewsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
